Added a functional private secret manager example
terraform-ibm-modules/terraform-ibm-secrets-manager-iam-engine pull request #78
Opened 2024-04-10 16:37 UTC by kierramarie

### Description

A private only secret manager example was added to this repo. All endpoint_types have been set to private for this example. It has been tested in schematics.

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2024-04-10 16:42 UTC, kierramarie commented
/run pipeline

2024-04-11 09:28 UTC, ocofaigh commented on examples/private/README.md
> +# Basic example
Private example

Also update the content below since its a private only example

2024-04-11 09:30 UTC, ocofaigh requested changes
Can you update `.catalog-onboard-pipeline.yaml` to add the new example to it, and also update the [flavors](https://github.com/terraform-ibm-modules/terraform-ibm-secrets-manager-iam-engine/blob/880ebcc8bc7f8b32a65553669861afb61961c1fb/ibm_catalog.json#L47) array in the ibm_catalog.json with the new example too

2024-04-11 14:33 UTC, kierramarie commented on examples/private/README.md
> +# Basic example
Let me know if there is anything else you'd like me to add to the docs.

2024-04-11 15:36 UTC, kierramarie commented
/run pipeline

2024-04-11 16:24 UTC, ocofaigh requested changes
see latest comments

2024-04-11 16:24 UTC, ocofaigh commented on ibm_catalog.json
> +          "working_directory": "examples/private"
you need to also include and `architecture` section. Just copy same format as basic example

2024-04-11 16:24 UTC, ocofaigh commented on ibm_catalog.json
> +          "label": "Private Only",
Maybe just call it `Private` ?

2024-04-11 20:08 UTC, kierramarie commented
/run pipeline

2024-04-12 09:49 UTC, ocofaigh approved these changes

2024-04-12 09:49 UTC, merged

2024-04-29 14:55 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 1.1.1 :tada:

The release is available on [GitHub release](https://github.com/terraform-ibm-modules/terraform-ibm-secrets-manager-iam-engine/releases/tag/v1.1.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: