fix: bump secrets manager and IBM provider
terraform-ibm-modules/terraform-ibm-secrets-manager-iam-engine pull request #86
Opened 2024-04-25 17:28 UTC by shemau

### Description

Bump IBM Provider to 1.62.0 and update secrets manager above 1.5.0 which required service_endpoints to be renamed allowed_network.

### Release required?

- [ ] No release
- [x] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

Bump IBM Provider to 1.62.0

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2024-04-25 17:30 UTC, alex-reiff submitted a review, later dismissed

2024-04-25 22:56 UTC, shemau commented
/run pipeline

2024-04-28 16:14 UTC, shemau commented
/run pipeline

2024-04-29 13:39 UTC, ocofaigh requested changes
1 minor comment

2024-04-29 13:39 UTC, ocofaigh commented on version.tf
> +      version = ">= 1.62.0"
Hmm, this should be `>= 1.62.0, <2.0.0` like our other modules. Must have been missed when that was rolled out.

2024-04-29 14:24 UTC, shemau commented
/run pipeline

2024-04-29 14:53 UTC, ocofaigh approved these changes

2024-04-29 14:54 UTC, merged

2024-04-29 14:54 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 1.1.1 :tada:

The release is available on [GitHub release](https://github.com/terraform-ibm-modules/terraform-ibm-secrets-manager-iam-engine/releases/tag/v1.1.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: